baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Diploma de Especialización en Ciencia de datos geográficos"
theme = "material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeurls = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Aitor Ameztegui"
  bio = ""
  job = "Profesor Agregado"
  location = "Universitat de Lleida"
  gravatarEmail = "aitor.ameztegui@udl.cat"
  # Your profile picture
#  picture = ""º
  twitter = "multivac42"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Inicio"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "syllabus"
  name = "Plan de estudios"
  pre = "<i class=\"material-icons\">date_range</i>"
  url = "/syllabus"
[[menu.main]]
  weight = 3
  identifier = "policies"
  name = "Información"
  pre = "<i class=\"material-icons\">info</i>"
  url = "/info"
[[menu.main]]
  weight = 4
  identifier = "preinscripcion"
  name = "Preinscripción"
  pre = "<i class=\"material-icons\">checklist_rtl</i>"
  url = "/preinscripcion"


[[menu.footer]]
  weight = 1
  identifier = "Lleida"
  name = "Universidad de Zaragoza"
  pre = "<i class='fa fa-university fa-lg'></i>"
  url = "https://www.unizar.es/"
[[menu.footer]]
  weight = 2
  name = "Preinscripción"
  pre = "<i class=\"icon-rlogo\" style=\"font-size:150%\"></i>"
  url = "https://geodataunizar.netlify.app/preinscripcion/"
[[menu.footer]]
  weight = 3
  identifier = "GitHub"
  name = "GitHub"
  pre = "<i class=\"button-icon fa fa-2x fa-github\"></i>"
  url = "https://github.com/ameztegui/web_master_geodata"
[[menu.footer]]


[params]
  dateFormat = "January 2, 2006"
  background = "img/background5.png"
  favicon = "img/udl_logo.ico"
